# Generated by Django 5.1.3 on 2025-02-20 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('time', models.DecimalField(decimal_places=1, max_digits=3)),
                ('description', models.TextField()),
                ('body', models.TextField()),
                ('author', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SymmetricalNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='third_app.note')),
                ('second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='third_app.note')),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='links',
            field=models.ManyToManyField(through='third_app.SymmetricalNotes', to='third_app.note'),
        ),
    ]
