# Generated by Django 5.1.3 on 2025-02-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='time',
            field=models.TimeField(),
        ),
    ]
