# Generated by Django 5.1.3 on 2025-04-04 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third_app', '0003_alter_note_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('time', models.DateTimeField()),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=20)),
                ('links', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='third_app.note')),
            ],
        ),
    ]
