# Generated by Django 5.1.3 on 2025-04-04 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third_app', '0004_masternote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masternote',
            name='links',
        ),
        migrations.CreateModel(
            name='NotesToMasterNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='third_app.masternote')),
                ('second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_to_masternote', to='third_app.note')),
            ],
        ),
        migrations.AddField(
            model_name='masternote',
            name='links',
            field=models.ManyToManyField(through='third_app.NotesToMasterNote', to='third_app.note'),
        ),
    ]
