# Generated by Django 5.1.3 on 2025-04-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third_app', '0005_remove_masternote_links_notestomasternote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
