# Generated by Django 5.1.3 on 2025-04-11 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third_app', '0006_noteimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotesToImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='third_app.note')),
                ('second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_to_note', to='third_app.noteimage')),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='images',
            field=models.ManyToManyField(through='third_app.NotesToImage', to='third_app.noteimage'),
        ),
    ]
