# Generated by Django 5.1.3 on 2025-04-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third_app', '0007_notestoimage_note_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteimage',
            name='img',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
